package ar.com.bluesoftware.universidad.vista;

import ar.com.bluesoftware.universidad.accesoDatos.Materia_Datos;
import ar.com.bluesoftware.universidad.entidades.Materia;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author Juan
 */
public class Form_Materia extends javax.swing.JInternalFrame {

    Materia materia;
    Materia_Datos matData;
    private Session session;

    /**
     * Creates new form Form_Materia
     */
    public Form_Materia(Session session) {
        initComponents();

        // Inicializar el objeto Materia_Datos
        this.session = session;
        matData = new Materia_Datos(this.session);
        System.out.println("Form_Materia: Sesión recibida y asignada correctamente.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        botonNuevo = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jtCodigo = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Vollkorn Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Formulario de Materias");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 330, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 40, 585, 10));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Codigo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 106, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 212, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Año:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 322, -1, -1));

        botonBuscar.setBackground(new java.awt.Color(102, 102, 255));
        botonBuscar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscar.setText("Buscar");
        botonBuscar.setPreferredSize(new java.awt.Dimension(70, 30));
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 99, 100, -1));

        botonLimpiar.setBackground(new java.awt.Color(102, 102, 255));
        botonLimpiar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        botonLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        botonLimpiar.setText("Limpiar");
        botonLimpiar.setPreferredSize(new java.awt.Dimension(70, 30));
        getContentPane().add(botonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 190, 100, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Estado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 421, -1, -1));
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 421, -1, 16));

        jLabel6.setText("Activa o Desactiva");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 443, -1, -1));

        botonNuevo.setBackground(new java.awt.Color(102, 102, 255));
        botonNuevo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        botonNuevo.setForeground(new java.awt.Color(255, 255, 255));
        botonNuevo.setText("Nuevo");
        botonNuevo.setPreferredSize(new java.awt.Dimension(70, 30));
        getContentPane().add(botonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 603, 80, -1));

        botonGuardar.setBackground(new java.awt.Color(102, 102, 255));
        botonGuardar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardar.setText("Guardar");
        botonGuardar.setPreferredSize(new java.awt.Dimension(70, 30));
        getContentPane().add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 600, 90, -1));

        botonEliminar.setBackground(new java.awt.Color(102, 102, 255));
        botonEliminar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminar.setText("Eliminar");
        botonEliminar.setPreferredSize(new java.awt.Dimension(70, 30));
        getContentPane().add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 603, 90, -1));

        botonSalir.setBackground(new java.awt.Color(102, 102, 255));
        botonSalir.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("Salir");
        botonSalir.setPreferredSize(new java.awt.Dimension(70, 40));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 600, 80, 30));
        getContentPane().add(jtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 230, 30));
        getContentPane().add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 230, 30));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 312, 110, 30));

        setBounds(0, 0, 683, 680);
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // Obtener el código ingresado por el usuario
        String codigoTexto = jtCodigo.getText();

        try {
            // Convertir el texto ingresado a un número entero
            int idMateria = Integer.parseInt(codigoTexto);
            // Realizar la búsqueda en la base de datos
            materia = matData.obtenerMateria(idMateria);

            // Verificar si se encontró la materia
            if (materia != null) {
                // Mostrar los datos de la materia en los JTextField correspondientes
                jtNombre.setText(materia.getNombre());
                jTextField1.setText(String.valueOf(materia.getAnio()));
                // Otros campos si los hay
            } else {
                // Si no se encuentra la materia, limpiar los JTextField
                limpiarCampos();
                JOptionPane.showMessageDialog(this, "Materia no encontrada", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            // Manejar el caso en que el usuario ingrese un valor no numérico
            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // Boton Salir
        cerrarVentana();
    }//GEN-LAST:event_botonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables

    public void desactivarCampos() {

    }

    public void habilitarCampos() {

    }

    public void limpiarCampos() {

    }

    private void cerrarVentana() {
        // Oculta la ventana
        this.setVisible(false);
        // Libera recursos asociados a la ventana
        this.dispose();
    }

}
