package ar.com.bluesoftware.universidad.vista;

import ar.com.bluesoftware.universidad.accesoDatos.Alumno_Datos;
import ar.com.bluesoftware.universidad.accesoDatos.Inscripcion_Datos;
import ar.com.bluesoftware.universidad.accesoDatos.Materia_Datos;
import ar.com.bluesoftware.universidad.entidades.Alumno;
import ar.com.bluesoftware.universidad.entidades.Inscripcion;
import ar.com.bluesoftware.universidad.entidades.Materia;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;

/**
 *
 * @author Juan
 */
public class MenuAdmin extends javax.swing.JInternalFrame {

    private JScrollPane scrollPane1;
    private JScrollPane scrollPane12;
    private DefaultTableModel modeloTabla1;
    private DefaultTableModel modeloTabla2;
    private Alumno a1;
    private Alumno_Datos alumno_Data;
    private Inscripcion ins;
    private Inscripcion_Datos ins_data;
    private Materia_Datos matData;
    private Session session;

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin(Session session) {
        initComponents();
        agregarTabla();
        //((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null); //Elimina encabezado de ventana

        desactivarCampos();
        this.session = session;
        this.alumno_Data = new Alumno_Datos(this.session);
        ins_data = new Inscripcion_Datos(this.session);
        System.out.println("Form_Alumno: Sesión recibida y asignada correctamente.");

        cargarCombo();
        // Llamar al método agregarTabla y cargarTabla para inicializar las tablas

        // Configura un ActionListener para el botón Salir
        botonSalir.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cerrarVentana();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        nota = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Inscripto = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        noInscripto = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        botonInscribir = new javax.swing.JButton();
        Anular = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Vollkorn Bold", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Listado de Alumnos por Materias");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 630, 10));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Seleccione un Alumno:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 214, -1));

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabla1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 510, 250));
        jPanel2.add(nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 67, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Ingrese la Nueva Nota");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, -1, -1));

        botonGuardar.setBackground(new java.awt.Color(102, 102, 255));
        botonGuardar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardar.setText("Guardar");
        botonGuardar.setPreferredSize(new java.awt.Dimension(70, 30));
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 100, -1));

        botonSalir.setBackground(new java.awt.Color(102, 102, 255));
        botonSalir.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("Salir");
        botonSalir.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel2.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, 90, -1));

        jTabbedPane1.addTab("Manejo de Notas", jPanel2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Vollkorn Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Formulario de Inscripcion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 360, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Seleccione un Alumno:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 164, -1));

        ComboBox1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(ComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 240, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Listado de Materias");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Materias Inscriptas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, 30));

        Inscripto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscriptoActionPerformed(evt);
            }
        });
        jPanel1.add(Inscripto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Materias no Inscriptas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, 30));

        noInscripto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noInscriptoActionPerformed(evt);
            }
        });
        jPanel1.add(noInscripto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        Tabla.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 530, 250));

        botonInscribir.setBackground(new java.awt.Color(102, 102, 255));
        botonInscribir.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        botonInscribir.setForeground(new java.awt.Color(255, 255, 255));
        botonInscribir.setText("Inscribir");
        botonInscribir.setPreferredSize(new java.awt.Dimension(100, 30));
        botonInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInscribirActionPerformed(evt);
            }
        });
        jPanel1.add(botonInscribir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, -1, -1));

        Anular.setBackground(new java.awt.Color(102, 102, 255));
        Anular.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Anular.setForeground(new java.awt.Color(255, 255, 255));
        Anular.setText("Anular Inscripcion");
        Anular.setPreferredSize(new java.awt.Dimension(120, 30));
        Anular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnularActionPerformed(evt);
            }
        });
        jPanel1.add(Anular, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, 180, -1));

        Salir.setBackground(new java.awt.Color(102, 102, 255));
        Salir.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.setPreferredSize(new java.awt.Dimension(70, 30));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 600, 80, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 500, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 620, 10));

        jTabbedPane1.addTab("Inscripciones", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 720, 670));

        setBounds(0, 0, 725, 707);
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox1ActionPerformed

    }//GEN-LAST:event_ComboBox1ActionPerformed

    private void InscriptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscriptoActionPerformed

    }//GEN-LAST:event_InscriptoActionPerformed

    private void noInscriptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noInscriptoActionPerformed

    }//GEN-LAST:event_noInscriptoActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked

    }//GEN-LAST:event_TablaMouseClicked

    private void botonInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInscribirActionPerformed

    }//GEN-LAST:event_botonInscribirActionPerformed

    private void AnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnularActionPerformed

    }//GEN-LAST:event_AnularActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // Boton salir
        cerrarVentana();
    }//GEN-LAST:event_SalirActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // Combo Box
        cargarCombo();


    }//GEN-LAST:event_jComboBoxActionPerformed

    private void Tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabla1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anular;
    private javax.swing.JComboBox<Alumno> ComboBox1;
    private javax.swing.JRadioButton Inscripto;
    private javax.swing.JButton Salir;
    private javax.swing.JTable Tabla;
    private javax.swing.JTable Tabla1;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonInscribir;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton noInscripto;
    private javax.swing.JTextField nota;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo() {
        ins = new Inscripcion();
        matData = new Materia_Datos(session);
        
        // Crear una única instancia de Alumno_Datos en el constructor
        if (alumno_Data == null) {
            alumno_Data = new Alumno_Datos(session);
        }

        // Obtener el alumno seleccionado en el JComboBox
        a1 = (Alumno) jComboBox.getSelectedItem();

        // Verificar si se seleccionó un alumno
        if (a1 != null) {
            // Llamar al método obtenerMateriasCursadas para obtener la lista de materias cursadas para el alumno seleccionado
            List<Materia> materiasCursadas = matData.obtenerMateriasCursadasPorAlumno(a1);
            if (materiasCursadas != null) {
                // Limpiar la tabla antes de agregar nuevas filas
                DefaultTableModel modeloTabla = (DefaultTableModel) Tabla1.getModel();
                modeloTabla.setRowCount(0);
                // Agregar las materias cursadas a la tabla Tabla1
                for (Materia mat : materiasCursadas) {
                    // Agrega una fila con los datos de la materia
                    modeloTabla.addRow(new Object[]{mat.getIdMateria(), mat.getNombre()});
                }
            }
        }
    }

    private void agregarTabla() {
        // Agregar tabla a la primera pestaña
        scrollPane1 = new JScrollPane();
        modeloTabla1 = new DefaultTableModel(); // Nuevo modelo de tabla
        modeloTabla1.addColumn("Codigo");
        modeloTabla1.addColumn("Nombre");
        modeloTabla1.addColumn("Nota");
        Tabla1.setModel(modeloTabla1); // Establecer el modelo a la tabla
        scrollPane1.setViewportView(Tabla1);
        jPanel2.add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 510, 200));

        // Agregar tabla a la segunda pestaña
        scrollPane12 = new JScrollPane();
        modeloTabla2 = new DefaultTableModel(); // Nuevo modelo de tabla
        modeloTabla2.addColumn("id");
        modeloTabla2.addColumn("Nombre");
        modeloTabla2.addColumn("Año");
        Tabla.setModel(modeloTabla2); // Establecer el modelo a la tabla
        scrollPane12.setViewportView(Tabla);
        jPanel1.add(scrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 530, 250));
    }

    

    public void desactivarCampos() {

    }

    public void habilitarCampos() {

    }

    public void limpiarCampos() {

    }

    private void cerrarVentana() {
        // Oculta la ventana
        this.setVisible(false);
        // Libera recursos asociados a la ventana
        this.dispose();
    }

    public void cerrarSesion() {
        if (session != null && session.isOpen()) {
            session.close();
            System.out.println("Sesión cerrada correctamente.");
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        // Configura un color transparente para el fondo
        Color transparentColor = new Color(0, 0, 0, 0); // R, G, B, Alpha
        g.setColor(transparentColor);
        g.fillRect(0, 0, getWidth(), getHeight());
    }
}
